"Myślę o dwu czarnych bluzach w stylu sportowym"
"Myślę o dwu czarnych kimonach na co dzień"
"Myślę o dwu czarnych kimonach w stylu sportowym"
"Myślę o dwu czarnych koszulkach w stylu sportowym"
"Myślę o dwu czarnych swetrach od znanego projektanta"
"Myślę o dwu ekologicznych koszulkach od znanego projektanta"
"Myślę o dwu ekologicznych swetrach w stylu sportowym"
"Myślę o dwu wykonanych z wełny bluzach w stylu sportowym"
"Myślę o dwu wykonanych z wełny swetrach na co dzień"
"Myślę o trzech czarnych kimonach na co dzień"
"Myślę o trzech czarnych kimonach od znanego projektanta"
"Myślę o trzech czarnych koszulce w stylu sportowym"
"Myślę o trzech czarnych swetrach na co dzień"
"Myślę o trzech ekologicznych bluzach na co dzień"
"Myślę o trzech ekologicznych koszulkach na co dzień"
"Myślę o trzech ekologicznych swetrach od znanego projektanta"
"Myślę o trzech ekologicznych swetrach w stylu sportowym"
"Myślę o trzech wykonanych z wełny kimonach w stylu sportowym"
"Myślę o trzech wykonanych z wełny koszulkach na co dzień"
# sorted, and uniq'ed 
