("Uniwersytet Papieski im. Jana Pawła II", "gen", "Uniwersytetu Papieskiego im. Jana Pawła II")
("Maciej Kowalski", "dat:pl", "Maciejom Kowalskim")
("Anna Komorowska-Zielińska", "gen", "Anny Komorowskiej-Zielińskiej")
("Kalwaria Zebrzydowska", "dat", "Kalwarii Zebrzydowskiej")
("Królowa Elżbieta II", "inst", "Królową Elżbietą II")
("Królowa Elżbieta druga", "inst", "Królową Elżbietą drugą")
("PZPR", "dat", "PZPR-owi")
("PZPR", "nom", "PZPR")
("Góry Błękitne", "gen", "Gór Błękitnych")
("siódmy stycznia", "inst", "siódmym stycznia")
("godzina piętnasta", "pl:dat", "godzinom piętnastym")
("Polskie Górnictwo Gazowe i Naftownictwo", "inst", "Polskim Górnictwem Gazowym i Naftownictwem")
("Wydział Dziennikarstwa i Nauk Politycznych UW", "dat", "Wydziałowi Dziennikarstwa i Nauk Politycznych UW")
("Wojewódzki Ośrodek Ruchu Drogowego", "pl:gen", "Wojewódzkich Ośrodków Ruchu Drogowego")
("swoje własne dzieci", "gen:sg", "swego własnego dziecka")
("biała flaga z papieru", "gen:pl", "białych flag z papieru")
("biała jak sól, flaga z szorstkiego płótna", "pl:dat", "białym jak sól, flagom z szorstkiego płótna")
("połowa kilograma", "gen", "połowy kilograma")
("dwoje dzieci", "inst", "dwoma dziećmi")
("troje oczu", "inst", "trzema oczami")
("czworo młodych uszu", "loc", "czworgu młodych uszach")
("dziesięcioro skrzypiec", "loc", "dziesięciu skrzypcach")
("3 świnie", "loc", "3 świniach")
("cztery ściany", "dat", "czterem ścianom")
("trzy i pół tysiąca", "gen", "trzech i pół tysiąca")
("drzewa i dwoje małych dzieci", "dat", "drzewom i dwojgu małym dzieciom")
("trzy małe świnki", "dat", "trzem małym świnkom")
("sześć kwadratów i trójkątów", "loc", "sześciu kwadratach i trójkątach")
("sześć małych i złotych łańcuszków", "dat", "sześciu małym i złotym łańcuszkom")
("sto psów", "dat", "stu psom")
("milion złotych", "inst", "milionem złotych")
("jeden głupi wyraz", "loc", "jednym głupim wyrazie")
("pięciu łysych mężczyzn", "inst", "pięcioma łysymi mężczyznami")
("wysokiemu i czarno-zielonemu", "gen:pl", "wysokich i czarno-zielonych")
("biały jak kreda", "com", "bielszy jak kreda")
("biały i gładki", "sup:f", "najbielsza i najgładsza")
("pieprz, sól i mąka", "gen", "pieprzu, soli i mąki")
("kraina mlekiem i miodem płynąca", "pl:dat", "krainom mlekiem i miodem płynącym")
("czarny chleb i czarna kawa", "inst", "czarnym chlebem i czarną kawą")
("patrzeć", "ger", "patrzenie")
("zabijać", "ger:dat", "zabijaniu")
("zabijacie", "impt", "zabijajcie")
("zabijać", "impt:pl:pri", "zabijajmy")
("zabijać", "ppas:neg", "niezabijany")
("profesorowie", "depr", "profesory")
("biały", "adja", "biało")
("pies", "gen", "psa")
("człowiek", "pl", "ludzie")
("sitko", "inst", "sitkiem")
("widły", "pl:inst", "widłami")
("czeluść", "dat", "czeluści")
("świece", "dat:sg", "świecy")
("psom", "sg", "psu")
("piękny", "gen", "pięknego")
("zły", "pl", "źli")
("zwykły", "f", "zwykła")
("zwykłego", "f", "zwykłej")
("jasny", "f:pl:gen", "jasnych")
("ciemny", "f:pl:acc", "ciemne")
("białych", "sg:m3:acc", "biały")
("biała", "pl:m1", "biali")
("biała", "pl:m3", "białe")
("biała", "sup", "najbielsza")
("biegnący", "pl:gen", "biegnących")
("stojący", "f:neg:pl:dat", "niestojącym")
("stojący", "f:neg:pl:dat", "niestojącym")
("widzenie", "pl", "widzenia")
("widzenie", "neg", "niewidzenie")
("oddychanie", "dat", "oddychaniu")
("widzę", "pl", "widzimy")
("widzę", "ter", "widzi")
("widzę", "sec:pl", "widzicie")
("leczy", "pl", "leczą")
("leczy", "pl:sec", "leczycie")
("leczył", "f", "leczyła")
